install! 'cocoapods',
  :disable_input_output_paths => true,
  :warn_for_multiple_pod_sources => false

platform :ios, '10.0'
inhibit_all_warnings!

target 'RSKExample' do
  pod 'OCMock','~> 3.4.3'
  pod 'XcodeCoverage', '1.4.2'
  pod 'FMDB', '>= 2.7.0'
  pod 'FuckKit',:inhibit_warnings => false, :path => '../'
end

target 'RSKToday' do
  pod 'OCMock','~> 3.4.3'
  pod 'XcodeCoverage', '1.4.2'
  pod 'FMDB', '>= 2.7.0'
  pod 'FuckKit',:inhibit_warnings => false, :path => '../'
end

def update_deployment_config(config = nil)
  return if config.nil?
  config.build_settings['ENABLE_BITCODE'] = 'NO'
  if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    update_deployment_config(config)
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      update_deployment_config(config)
    end
  end
  ## for generate_multiple_pod_projects = true
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
      update_deployment_config(config)
    end
    
    project.targets.each do |target|
      target.build_configurations.each do |config|
        update_deployment_config(config)
      end
    end
  end

end

